-- CREATING THE DATABASE
CREATE DATABASE CRUD;

-- USING DATABASE
use CRUD;

-- CREATING A TABLE
CREATE TABLE comprador (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    address VARCHAR(50) NOT NULL,
    phone VARCHAR(20)
);

-- MOSTRATE TABLES
SHOW TABLES;

--DESCRIPCION DE LAS TABLAS
describe comprador;